locallibrary/catalog/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

#app_name = 'catalog'

urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),
    path('author/create/', views.AuthorCreate.as_view(), name='author-create'),
    path('author/<int:pk>/update/', views.AuthorUpdate.as_view(), name='author-update'),
    path('author/<int:pk>/delete/', views.AuthorDelete.as_view(), name='author-delete'),
    path('author/', views.AuthorListView.as_view(), name='author'),
    path('author/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
    path('books/create/', views.BookCreate.as_view(), name='book-create'),
    path('books/<int:pk>/update/', views.BookUpdate.as_view(), name='book-update'),
    path('books/<int:pk>/delete/', views.BookDelete.as_view(), name='book-delete'),
    path('allbooks/', views.LoanedBooksByAllUsersListview.as_view(), name='all-users-borrowed'),
    path('login/', views.user_login, name='user_login'),
    url(r'^register/', views.register, name='user_regis'),
]

locallibrary/locallibrary/urls.py
from django.contrib import admin
from django.urls import path, include
import os
from django.views.generic import RedirectView
from django.conf.urls.static import static
from django.conf.urls import url
from django.conf import settings
from catalog import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='catalog/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
    path('logout/', views.user_logout, name='logout'),
    path('special/', views.special, name='spec'),
    #path('register/', views.register, name='formregis'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

locallibrary/catalog/models.py
from django.db import models
from django.urls import reverse #used to generate urls by reversing url patterns
import uuid #required for unique book instances/copies
from django.contrib.auth.models import User
from datetime import date


# Create your models here.
class Genre(models.Model):
    '''Model representing a book genre'''
    name = models.CharField(max_length=200, help_text="Enter a book Genre(ex: fiction/non-fiction")

    def __str__(self):
        '''String method for representing the model object'''
        return self.name

class Language(models.Model):
    name = models.CharField(max_length=100, help_text="Langauge in which the book is published")

    def get_absolute_url(self):
        '''return the url to access a particular language instance'''
        return reverse('', args=[str(self.id)])

    def __str__(self):
        return self.name

class Book(models.Model):
    '''Model representing a book(but not a specific copy of a book'''
    title = models.CharField(max_length=200)

    #to declare author now, i have used foreignkey because book can have only one author whereas author may have
    #multiple books published in his name.also Author is declared as string rather than the object because it hasnt
    #been declared yet in file
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)

    summary = models.TextField(max_length=1000, help_text="Give a description about this book")
    isbn = models.CharField('ISBN', max_length=13, unique=True, help_text='refer mozilla')

    #ManyToManyField is used in genre filed because genre can contain many books and book can contain mant genres
    #Genre class is already defined so instead of string we can just mention genre field name in the parameter
    genre = models.ManyToManyField(Genre, help_text="Select a genre for this book")

    language = models.ForeignKey('Language', on_delete=models.SET_NULL, null=True)
    #language = models.CharField(max_length=50, help_text="Language in which a book is published")

    def __str__(self):
        return self.title
        '''string for reprsenting a model object'''


    def display_genre(self):
        '''creating a string for the genre.this is required to run display_genre in admin.py'''
        return ', '.join(genre.name for genre in self.genre.all()[:3])


    def get_absolute_url(self):
        '''returns the url to access a detail record for this book'''
        return reverse('book-detail', args=[str(self.id)])

class BookInstance(models.Model):
    '''Model reprsenting a specific copy of a book(that is borrowed from llocal library)'''
    id = models.UUIDField(primary_key=True, default=uuid.uuid4(), editable=True, help_text="Unique ID of this book")
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    LOAN_STATUS = (
        ('m', "Maintainance"),
        ('o', "On Loan"),
        ('a', "Available"),
        ('r', "Reserved")
    )
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)


    status=models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text='Book Availability')

    class Meta:
        ordering = ['due_back']
        permissions = (("can_mark_returned", "Set book as returned"),)

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False


    def __str__(self):
        return f'{self.id} ({self.book})'




class Author(models.Model):
    '''Model representing an author'''
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        '''return the url to access a particular author instance'''
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        return f'{self.last_name}, {self.first_name}'

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User, on_delete=models.SET_NULL, null=True)

    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pic', blank=True)

    def __str__(self):
        return User.username

locallibrary/catalog/forms.py
from django import forms
import datetime
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

from django.contrib.auth.models import User
from catalog.models import UserProfileInfo

class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(help_text="Enter a date between today and the 4th week(default is 3)")

    def clean_renewal_date(self):
        data = self.clean_renewal_date['renewal_date']

        #check if date is not in the past
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'),)

        #check if a date is in the allowed range(+4 weeks from today)
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'), )

        return data

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

locallibrary/catalog/views.py
from .models import Book, BookInstance, Author, Genre, Language
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin

import datetime
from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from .forms import RenewBookForm

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from django.urls import reverse
from django.contrib.auth import authenticate, logout, login
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required

from catalog.forms import UserForm, UserProfileInfoForm
# Create your views here.

class BookListView(generic.ListView):
    model = Book

class BookDetailView(generic.DetailView):
    model = Book

class AuthorListView(generic.ListView):
    model = Author

class AuthorDetailView(generic.DetailView):
    model = Author

def index(request):
    '''veiw function for homepage of site'''

    '''i) generate count of some of the main objects(books,copies)'''
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()

    '''ii) available books(status = 'a')'''
    book_status = BookInstance.objects.filter(status__exact='a').count()

    '''iii) no of authors.. note: all() will be implied by default if its not typed'''
    no_of_authors = Author.objects.count()

    no_of_genre_category = Genre.objects.all().count()

    num_of_languages = Language.objects.all().count()

    '''No of visits to this view as counted in session variable'''

    num_visits = request.session.get('num_visits', 1)
    request.session['num_visits'] = num_visits + 1


    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'book_status': book_status,
        'no_of_authors': no_of_authors,
        'no_of_genre_category': no_of_genre_category,
        'num_visits': num_visits,
        'num_of_languages': num_of_languages,

    }


    '''render the HTML template index.html with the data in context variable'''
    return render(request, 'index.html', context=context)

   #creating view for on-loan details of particular user
class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
        '''generic class based view listings boooks on loan to current user'''
        model = BookInstance
        template_name = 'catalog/book_instance_list_borrowed_user.html'
        paginate_by = 3

        def get_queryset(self):
            return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')


@login_required
#@permission_required('catalog.can_mark_returned', raise_exception=True)
def renew_book_librarian(request, pk):
    '''view function for creating a specific book instance y librarian'''
    book_instance = get_object_or_404(BookInstance, pk=pk)

    #if this is a POST request then process the form data
    if request.method == 'POST':
        #create a form instance and populate it with data from the request(binding)
        form = RenewBookForm(request.POST)

        #check if the form is valid:
        if form.is_valid():
            #process the data in form.cleaned_data as required(here we just write it to model due_back field)

            book_instance.due_back = form.cleaned_data['renewal_date']
            book_instance.save()

            #redirect to a new URL:
            return HttpResponseRedirect(reverse('books'))
    #If this is a GET create a default form
    else:
        proposed_renewal_date= datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookForm(initial={'renewal_date': proposed_renewal_date})

    context = {
        'form': form,
        'book_instance': book_instance,
    }
    return render(request, 'catalog/book_renew_librarian.html', context)

class AuthorCreate(CreateView):
    model = Author
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']


class AuthorUpdate(UpdateView):
    model = Author
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']

class AuthorDelete(DeleteView):
    model = Author
    success_url = reverse_lazy('Authors')

class BookCreate(CreateView):
    model = Book
    fields = ['title', 'author', 'genre', 'isbn', 'summary']

class BookUpdate(UpdateView):
    model = Book
    fields = ['title', 'author', 'genre', 'isbn', 'summary']

class BookDelete(DeleteView):
    model = Book
    success_url = reverse_lazy('books')

#creating view for on-loan details of all users
class LoanedBooksByAllUsersListview(LoginRequiredMixin, generic.ListView):
    model = BookInstance
    template_name = 'catalog/book_instance_list_of_all_users_borrowed_visible_to_staffONLY.html'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(status__exact='o').order_by('due_back')


def user_login(request):
    if request.method == 'POST':

        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('catalog:index'))

            else:
                return HttpResponse("Account not active")
        else:
            print("Some tried to login and failed")
            print("username: {} and password:{} is not valid".format(username, password))
            return HttpResponse("Incorrect credentails supplied")
    else:
        return render(request, 'registration/login.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('user_login'))

@login_required
def special(request):
    return HttpResponse("You are logged in!!")

def register(request):
        registered = True
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

        context = {'user_form': user_form,
                   'profile_form': profile_form,
                   'registered': registered}

        return render(request, 'registration/formregis.html',
                  context)

locallibrary/catalog/templates/catalog/author_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1 style="padding-top: 300px;">Delete Author?</h1>

<p>Are you sure you want to delete the author: {{ author }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

locallibrary/catalog/templates/catalog/author_detail.html
{% extends "base_generic.html" %}

{% block content %}


  <h1 style="text-align:center">BioData:</h1>
  <div style="padding-left:50%">
    <p><strong>First Name:</strong> {{ author.first_name }}</a></p>
    <p><strong>Last Name:</strong> {{ author.last_name }}</p>
    <p><strong>DOB:</strong> {{ author.date_of_birth }}</p>
    <p><strong>DOD:</strong> {{ author.date_of_death }}</p>
    <p><strong>Books:</strong> {{ book.title.all }}</p>
  </div>
{% endblock %}

locallibrary/catalog/templates/catalog/author_form.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

locallibrary/catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1 style="text-align: center">Author List</h1>
  {% if author_list %}
  <ul style="padding-left: 50%">
    {% for author in author_list %}
      <li>
        <a href="{{ author.get_absolute_url }}">{{ author.first_name}} {{author.last_name }}</a>
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no author details available.</p>
  {% endif %}
{% endblock %}ml>

locallibrary/catalog/templates/catalog/book_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Book?</h1>

<p>Are you sure you want to delete the book: {{ book }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

locallibrary/catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Title: {{ book.title }}</h1>

  <p><strong>Author:</strong> <a href="{%url 'author' %}">{{ book.author }}</a></p> <!-- author detail link not yet defined -->
  <p><strong>Summary:</strong> {{ book.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p>
  <p><strong>Language:</strong> {{ book.language }}</p>
  <p><strong>Genre:</strong> {{ book.genre.all|join:", " }}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in book.bookinstance_set.all %}
      <hr>
      <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
        {{ copy.get_status_display }}
      </p>
      {% if copy.status != 'a' %}
        <p><strong>Due to be returned:</strong> {{ copy.due_back }}</p>
      {% endif %}
      <p><strong>Imprint:</strong> {{ copy.imprint }}</p>
      <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>
    {% endfor %}
  </div>
{% endblock %}

locallibrary/catalog/templates/catalog/book_form.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

locallibrary/catalog/templates/catalog/book_instance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1 style="text-align: center">Borrowed books</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %}
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'catalog:book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }})
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p style="padding-left:50%">Sorry.There are no books issued in your name.</p>
    {% endif %}
{% endblock %}

locallibrary/catalog/templates/catalog/book_instance_list_of_all_users_borrowed_visible_to_staffONLY.html
{% extends "base_generic.html" %}

{% block content %}
    <h1 style="text-align: center">All Borrowed Books</h1>

    {% if bookinstance_list %}
        <ul>

            {% for bookinst in bookinstance_list %}
               <li class="{% if bookinst %}text-success{% endif %}">
                  <a href="{% url 'catalog:book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }} - {{ bookinst.borrower }})
               </li>
            {% endfor %}
        </ul>
    {% else %}
        <p style="padding-left:50%">Sorry.There are no books issued to any of the users.</p>
    {% endif %}

{% endblock %}

locallibrary/catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1 style="text-align: center">Book List</h1>
  {% if book_list %}

  <ul style="padding-left:50%" >
    {% for book in book_list %}
      <li >
        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no books in the library.</p>
  {% endif %} 
{% endblock %}

locallibrary/catalog/templates/catalog/book_renew_librarian.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Renew: {{ book_instance.book.title }}</h1>
  <p>Borrower: {{ book_instance.borrower }}</p>
  <p{% if book_instance.is_overdue %} class="text-danger"{% endif %}>Due date: {{ book_instance.due_back }}</p>

  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}